version: "3.8"
services:
  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && chmod +x node_modules/.bin/nest && npm install @nestjs/config @nestjs/jwt @nestjs/passport bcryptjs passport-jwt && npm run start:dev"
    ports:
      - "5014:5014"
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_URI=mongodb://mongo:27017/plataformgame
      - JWT_SECRET=my_secret_jwt

  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install --legacy-peer-deps && npm start"
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local